/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * delevent.java
 *
 * Created on 17 Oct, 2011, 11:26:45 PM
 */

/**
 *
 * @author Home
 */
import java.awt.*;
import javax.swing.DefaultListModel;
import javax.swing.*;
import java.sql.*;
import javax.swing.ListModel;
public class delevent extends javax.swing.JFrame {

    /** Creates new form delevent */
    public delevent() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lb = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb.setModel(new DefaultListModel());
        lb.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lbValueChanged(evt);
            }
        });
        lb.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lbFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(lb);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 160, 80));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Events");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 170, 70));

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Delete.PNG"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, -1, -1));

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Download.PNG"))); // NOI18N
        jButton2.setText("Delete all Events");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, -1, -1));

        jButton3.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Back.PNG"))); // NOI18N
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Capture7.PNG"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lbFocusGained
 DefaultListModel l2=(DefaultListModel)lb.getModel();
        l2.clear();
        lb.setModel(l2);
        String sql2="select event from todolist;";
        try{
           Class.forName("java.sql.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","info");
           Statement s=con.createStatement();
           ResultSet rs=s.executeQuery(sql2);
           while(rs.next()==true)
           {
               String n=rs.getString("event");
               l2.addElement(n);
               lb.setModel(l2);
           }
            rs.close();
            s.close();
            con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_lbFocusGained

    private void lbValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lbValueChanged

    }//GEN-LAST:event_lbValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     int a=JOptionPane.showConfirmDialog(this,"Are yoy sure you want to exit");
        if(a==0) {
             try
{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","info");
    Statement s=con.createStatement();
    String sql="delete from todolist where event;" ;
    s.executeUpdate(sql);
    JOptionPane.showMessageDialog(this,"All events have been Deleted");
    s.close();
    con.close();
}
catch(Exception e)
{JOptionPane.showMessageDialog(this, e.getMessage());
  }
        }
        else if(a==1) {
            new delevent().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String w=(String)lb.getSelectedValue();
try
{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","info");
    Statement s=con.createStatement();

    String sql="delete from todolist where event=  '"+(w)+" ';" ;

    s.executeUpdate(sql);
       JOptionPane.showMessageDialog(this,"Event Deleted");
    s.close();
    con.close();


}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this, e.getMessage());
        }


 DefaultListModel l2=(DefaultListModel)lb.getModel();
        l2.clear();
        lb.setModel(l2);
        String sql2="select event from todolist;";
        try{
           Class.forName("java.sql.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","info");
           Statement s=con.createStatement();
           ResultSet rs=s.executeQuery(sql2);
           while(rs.next()==true)
           {
               String n=rs.getString("event");
               l2.addElement(n);
               lb.setModel(l2);
           }
            rs.close();
            s.close();
            con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
new allevents().setVisible(true);
dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new delevent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lb;
    // End of variables declaration//GEN-END:variables

}
