/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * insert.java
 *
 * Created on Aug 23, 2011, 9:55:38 AM
 */

/**
 *
 * @author Administrator
 */
import javax.swing.*;
import java.sql.*;
public class insert extends javax.swing.JFrame {

    /** Creates new form insert */
    public insert() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        t8 = new javax.swing.JTextField();
        b2 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("INSERT CONTENTS");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b1.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        b1.setForeground(new java.awt.Color(0, 0, 153));
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Tick.PNG"))); // NOI18N
        b1.setText("Submit");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 410, -1, -1));

        jLabel1.setText("Enter the employee number:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 160, 20));

        jLabel2.setText("Enter the Employee name:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 180, 160, 20));

        jLabel3.setText("Enter the DOB:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 160, 20));

        jLabel4.setText("Enter the date of join:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 160, 20));

        jLabel5.setText("Designation:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 160, 20));

        jLabel6.setText("Salary:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, 170, 20));

        jLabel7.setText("Leaves:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, 170, 20));

        jLabel8.setText("Rating:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 160, 20));

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 100, -1));

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 100, -1));

        t3.setText("yyyy-mm-dd");
        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        t3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t3FocusGained(evt);
            }
        });
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 100, -1));

        t4.setText("yyyy-mm-dd");
        t4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t4ActionPerformed(evt);
            }
        });
        t4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                t4FocusGained(evt);
            }
        });
        getContentPane().add(t4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 100, -1));

        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });
        getContentPane().add(t5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, 100, -1));

        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 100, -1));

        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });
        getContentPane().add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 330, 100, 20));

        t8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t8ActionPerformed(evt);
            }
        });
        getContentPane().add(t8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 100, -1));

        b2.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        b2.setForeground(new java.awt.Color(102, 0, 0));
        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Back.PNG"))); // NOI18N
        b2.setText("Back");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, -1, -1));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 0, 0));
        jLabel9.setText("RECRUITMENT");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 410, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/recruitment.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Yellow 3.PNG"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 480));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t4ActionPerformed
b1.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_t4ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
 String adno2="";
 int leaves=0;
 int error=0;
 int rating1=0;
         String dob2="";
        try
{
    Class.forName("java.sql.Driver");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","info");
    Statement s=con.createStatement();
    int empno=Integer.parseInt(t1.getText());
    String name=t2.getText();
    String name1=name.toUpperCase();
    String dob=t3.getText();
    String dob1=""+dob.charAt(0)+dob.charAt(1)+dob.charAt(2)+dob.charAt(3);
    int db=Integer.parseInt(dob1);

    String adno=t4.getText();
    String adno1=""+adno.charAt(0)+adno.charAt(1)+adno.charAt(2)+adno.charAt(3);
    int ad=Integer.parseInt(adno1);
    if(ad<=(db+20))
    {
      JOptionPane.showMessageDialog(this,"The DOB and DOJ do not seem factually correct");
      error=1;
    }
    else
    {
         adno2=t4.getText();
         dob2=t3.getText();
    }
    String status=t5.getText();
    String status1=status.toUpperCase();
    double salary=Double.parseDouble(t6.getText());
    int leaves_in_month=Integer.parseInt(t7.getText());
    if(leaves_in_month>=30)
    {
        JOptionPane.showMessageDialog(this,"The leaves in a month cannot be > 30");
        error=1;

    }
    else
    {
       leaves=leaves_in_month;
    }
    int rating=Integer.parseInt(t8.getText());
    if(rating>10)
    {
        JOptionPane.showMessageDialog(this,"The Rating cannot be greater than 10");
        error=1;
    }
    else
    {
       rating1=rating;
    }
    if(error==0)
    {
    String sql="insert into payroll1 values('"+empno+" ', '"+name1+" ', '"+dob2+" ', '"+adno2+" ', '"+status1+" ', '"+salary+" ', '"+leaves+" ', '"+rating1+" ');";
            s.executeUpdate(sql);
    JOptionPane.showMessageDialog(this,"This record has been successfully added");
    }
    else
    {
        JOptionPane.showMessageDialog(this,"Please check your error and try again");
        JOptionPane.showMessageDialog(this,"Record Not Updated");
    }
    t1.setText("");
    t2.setText("");
    t3.setText("yyyy-mm-dd");
    t4.setText("yyyy-mm-dd");
    t5.setText("");
    t6.setText("");
    t7.setText("");
    t8.setText("");
    s.close();
    con.close();
}
catch(Exception e)
{
    JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
new database().setVisible(true);
dispose();
    }//GEN-LAST:event_b2ActionPerformed

    private void t3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t3FocusGained
t3.setText("");
    }//GEN-LAST:event_t3FocusGained

    private void t4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_t4FocusGained
t4.setText("");
    }//GEN-LAST:event_t4FocusGained

    private void t8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t8ActionPerformed
b1.doClick();
    }//GEN-LAST:event_t8ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
b1.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
b1.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
b1.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
b1.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
b1.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
b1.doClick();        // TODO add your handling code here:
    }//GEN-LAST:event_t7ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new insert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    // End of variables declaration//GEN-END:variables

}
