/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * main.java
 *
 * Created on Aug 23, 2011, 9:09:56 AM
 */

/**
 *
 * @author Administrator
 */
import java.awt.*;
import javax.swing.DefaultListModel;
import javax.swing.*;
import java.sql.*;
import javax.swing.ListModel;
public class main extends javax.swing.JFrame {

    /** Creates new form main */
    public main() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        opt2 = new javax.swing.JRadioButton();
        opt1 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lb = new javax.swing.JList();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MAIN PAGE");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b10.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        b10.setForeground(new java.awt.Color(102, 0, 102));
        b10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logout_New.png"))); // NOI18N
        b10.setText("Sign Out");
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        getContentPane().add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, -1, -1));

        b11.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        b11.setText("DATABASE");
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });
        getContentPane().add(b11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 140, 30));

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("PAYROLL MANAGEMENT SYSTEM");
        jLabel2.setToolTipText("");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 680, 80));

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jButton1.setText("PERFORMANCE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 140, 30));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search By ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 0, 0))); // NOI18N
        jPanel1.setOpaque(false);

        buttonGroup1.add(opt2);
        opt2.setFont(new java.awt.Font("Monotype Corsiva", 2, 24)); // NOI18N
        opt2.setForeground(new java.awt.Color(0, 255, 0));
        opt2.setText("Emp no");
        opt2.setOpaque(false);
        opt2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                opt2ItemStateChanged(evt);
            }
        });
        opt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(opt1);
        opt1.setFont(new java.awt.Font("Monotype Corsiva", 2, 24)); // NOI18N
        opt1.setForeground(new java.awt.Color(51, 255, 51));
        opt1.setText("Name");
        opt1.setOpaque(false);
        opt1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                opt1ItemStateChanged(evt);
            }
        });
        opt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opt1ActionPerformed(evt);
            }
        });

        lb.setModel(new DefaultListModel());
        lb.setOpaque(false);
        lb.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lbValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lb);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(opt1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(opt2)
                .addGap(70, 70, 70))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opt1)
                    .addComponent(opt2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 270, 230));

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jButton2.setText("ORGANISER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 140, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Rose.PNG"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt2ActionPerformed

    private void opt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_opt1ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
int a=JOptionPane.showConfirmDialog(this,"Are you sure you want to Sign out");
if(a==0)
{
new login().setVisible(true);
dispose();
        }
else if(a==1)
{
new main().setVisible(true);
dispose();
}
    }//GEN-LAST:event_b10ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
new database().setVisible(true);
dispose();

    }//GEN-LAST:event_b11ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus

    }//GEN-LAST:event_formWindowGainedFocus

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new performance().setVisible(true);
dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void opt1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_opt1ItemStateChanged

        if((opt1.isSelected()==true))
        {
        DefaultListModel l2=(DefaultListModel)lb.getModel();
        l2.clear();
        lb.setModel(l2);
        String sql2="select name from payroll1;";
        try{
           Class.forName("java.sql.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","info");
           Statement s=con.createStatement();
           ResultSet rs=s.executeQuery(sql2);
           while(rs.next()==true)
           {
               String n=rs.getString("name");
               l2.addElement(n);
               lb.setModel(l2);
           }
            rs.close();
            s.close();
            con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(this, e.getMessage());
        }
         }
    }//GEN-LAST:event_opt1ItemStateChanged

    private void opt2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_opt2ItemStateChanged
        if((opt2.isSelected()==true))
        {
        DefaultListModel l2=(DefaultListModel)lb.getModel();
        l2.clear();
        lb.setModel(l2);
        String sql2="select empno from payroll1;";
        try{
           Class.forName("java.sql.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","info");
           Statement s=con.createStatement();
           ResultSet rs=s.executeQuery(sql2);
           while(rs.next()==true)
           {
               String n=rs.getString("empno");
               l2.addElement(n);
               lb.setModel(l2);
           }
            rs.close();
            s.close();
            con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(this, e.getMessage());
        }
         }
    }//GEN-LAST:event_opt2ItemStateChanged

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained

    }//GEN-LAST:event_formFocusGained

    private void lbValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lbValueChanged

    }//GEN-LAST:event_lbValueChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new todolist().setVisible(true);
dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JList lb;
    private javax.swing.JRadioButton opt1;
    private javax.swing.JRadioButton opt2;
    // End of variables declaration//GEN-END:variables

}
