/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * update.java
 *
 * Created on Aug 24, 2011, 1:35:24 PM
 */

/**
 *
 * @author Administrator
 */
import javax.swing.*;
import java.sql.*;
import javax.swing.DefaultListModel;
public class update extends javax.swing.JFrame {

    /** Creates new form update */
    public update() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        cb1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        l3 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("UPDATE RECORDS");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Update.PNG"))); // NOI18N
        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 360, -1, -1));

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Back.PNG"))); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, 120, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Roll No.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 255, 255))); // NOI18N
        jPanel1.setOpaque(false);

        cb1.setForeground(new java.awt.Color(51, 0, 255));
        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EmpNo", "Name", "DOB", "DOJ", "Designation", "Salary", "Leaves_in_Month", "Ratings" }));
        cb1.setEnabled(false);
        cb1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb1ItemStateChanged(evt);
            }
        });
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 190, 90));

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("UPDATE ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, 180, 30));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Roll No.", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 255, 255))); // NOI18N
        jPanel3.setOpaque(false);

        l3.setModel(new DefaultListModel());
        l3.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                l3ValueChanged(evt);
            }
        });
        l3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                l3FocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(l3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 220, 130));

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 0));
        jLabel2.setText("Enter The New Data:-");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 200, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Capture6.PNG"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void l3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_l3FocusGained

        DefaultListModel l1=(DefaultListModel)l3.getModel();
        l1.clear();
        l3.setModel(l1);
        String sql2="select EmpNo from payroll1;";
        try{
           Class.forName("java.sql.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","info");
           Statement s=con.createStatement();
           ResultSet rs=s.executeQuery(sql2);
           while(rs.next()==true)
           {
               String n=rs.getString("empno");
               l1.addElement(n);
               l3.setModel(l1);
           }
            rs.close();
            s.close();
            con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_l3FocusGained

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

String a=(String)l3.getSelectedValue();
int index=cb1.getSelectedIndex();
int b=Integer.parseInt(a);
String c=(String)cb1.getSelectedItem();
        if((index==0)||(index==6)||(index==7))
   {
       int d=Integer.parseInt(t1.getText());
       try{
                Class.forName("java.sql.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","info");
           Statement s=con.createStatement();

    String sql="update payroll1 set "+c+"='"+(d)+"' where EmpNo='"+(b)+"';";
           
           s.executeUpdate(sql);
           JOptionPane.showMessageDialog(this,"Record Updated");
           s.close();
           con.close();
}
catch(Exception e)
        {JOptionPane.showMessageDialog(this, e.getMessage());
        }
   }
else if((index==1)||(index==4)||(index==2)||(index==3))
   {
       String d1=(t1.getText());
       String d=d1.toUpperCase();
       try{
                Class.forName("java.sql.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","info");
           Statement s=con.createStatement();

    String sql="update payroll1 set "+c+"='"+(d)+"' where EmpNo="+(b)+";";

           s.executeUpdate(sql);
           JOptionPane.showMessageDialog(this,"Record Updated");
           s.close();
           con.close();
}
catch(Exception e)
        {JOptionPane.showMessageDialog(this, e.getMessage());
        }
   }
else if(index==5)
   {
       double d=Double.parseDouble(t1.getText());
       try{
                Class.forName("java.sql.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","info");
           Statement s=con.createStatement();

    String sql="update payroll1 set "+c+"='"+(d)+"' where EmpNo='"+(b)+"';";

           s.executeUpdate(sql);
           JOptionPane.showMessageDialog(this,"Record Updated");
           s.close();
           con.close();
}
catch(Exception e)
        {JOptionPane.showMessageDialog(this, e.getMessage());
        }
}

DefaultListModel l1=(DefaultListModel)l3.getModel();
        l1.clear();
          l3.setModel(l1);
        String sql2="select EmpNo from payroll1;";
        try{
           Class.forName("java.sql.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","info");
           Statement s=con.createStatement();
           ResultSet rs=s.executeQuery(sql2);
           while(rs.next()==true)
           {
               String n=rs.getString("empno");
               l1.addElement(n);
               l3.setModel(l1);
           }
            rs.close();
            s.close();
            con.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
new database().setVisible(true);
dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void l3ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_l3ValueChanged
cb1.setEnabled(true);

    }//GEN-LAST:event_l3ValueChanged

    private void cb1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb1ItemStateChanged
String a=(String)l3.getSelectedValue();
int b=Integer.parseInt(a);
int cb = cb1.getSelectedIndex();
String c=(String)cb1.getItemAt(cb);
        String sql2="select "+(c)+" from payroll1 where EmpNo ="+(b)+";";
        try{
           Class.forName("java.sql.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","info");
           Statement s=con.createStatement();
           ResultSet rs=s.executeQuery(sql2);
         while (rs.next()==true)
         {String k =(String)rs.getString(c);

           t1.setText(k);
         }
        }

        catch (Exception e)
        {JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_cb1ItemStateChanged

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new update().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JList l3;
    private javax.swing.JTextField t1;
    // End of variables declaration//GEN-END:variables

}
